export const table = [
  {
    index: "#",
    nome: "Nome",
    preco: "Preço",
    variacao24h: "24H",
    variacao7d: "7D",
    variacaoSemanal: "Últimos 7 dias",
  },
  {
    index: "1",
    nome: "Tether",
    preco: "R$ 5.77",
    variacao24h: 0.22,
    variacao7d: -3.22,
    variacaoSemanal: "-",
  },
  {
    index: "2",
    nome: "Bitcoin",
    preco: "R$ 492.651",
    variacao24h: -5.12,
    variacao7d: 1.12,
    variacaoSemanal: "-",
  },
  {
    index: "3",
    nome: "SushiSwap",
    preco: "R$ 3.66",
    variacao24h: 0.6,
    variacao7d: 3.6,
    variacaoSemanal: "-",
  },
  {
    index: "4",
    nome: "BitStamp",
    preco: "R$ 362.42",
    variacao24h: 0.6,
    variacao7d: -1.9,
    variacaoSemanal: "-",
  },
  {
    index: "5",
    nome: "Gemini",
    preco: "R$ 5.73",
    variacao24h: -0.08,
    variacao7d: 3.8,
    variacaoSemanal: "-",
  },
  {
    index: "6",
    nome: "Medibloc",
    preco: "R$ 0.03",
    variacao24h: 1.3,
    variacao7d: 10.4,
    variacaoSemanal: "-",
  },
  {
    index: "7",
    nome: "BRL",
    preco: "R$ 1.00",
    variacao24h: 1.69,
    variacao7d: -0.4,
    variacaoSemanal: "-",
  },
  {
    index: "8",
    nome: "KuCoin",
    preco: "R$ 64.41",
    variacao24h: 0.6,
    variacao7d: 3.6,
    variacaoSemanal: "-",
  },
  {
    index: "9",
    nome: "HexCoin",
    preco: "R$ 0.008121",
    variacao24h: 0.2,
    variacao7d: 1.6,
    variacaoSemanal: "-",
  },
  {
    index: "10",
    nome: "Decentraland",
    preco: "R$ 1.55",
    variacao24h: 0.2,
    variacao7d: 1.5,
    variacaoSemanal: "-",
  },
];
